### ISSUE TITLE
Nice work. Where can i find the saved weights for trained ESRGAN Generator?

### ISSUE THREAD

**Issue by keertika-j** [fenghansen/ESRGAN-Keras#1]
Nice work. Where can I find the saved weights for trained ESRGAN Generator?

**Comment by Sxs7513** [comment]
as above

**Comment by keertika-j** [comment]
as above?where?

**Comment by fenghansen** [comment]
Dear All,
    I have just uploaded my weights. I'm sorry that I couldn't upload the data to GitHub last month.
    Thanks for your attention!
Hansen

**Comment by fenghansen** [comment]
> as above?where?

I have just uploaded it once again.
